import turtle

turtlebot = turtle.Turtle()
turtlebot.teleport(-200, -100)
turtlebot.fillcolor("grey")
turtlebot.begin_fill()
turtlebot.forward(250)
turtlebot.right(90)
turtlebot.forward(-500)
turtlebot.right(90)
turtlebot.forward(250)
turtlebot.right(90)
turtlebot.forward(-500)
turtlebot.end_fill()
turtlebot.teleport(-175, -50)
turtlebot.setheading(0)
turtlebot.fillcolor("black")
turtlebot.begin_fill()
turtlebot.forward(200)
turtlebot.right(90)
turtlebot.forward(-400)
turtlebot.right(90)
turtlebot.forward(200)
turtlebot.right(90)
turtlebot.forward(-400)
turtlebot.end_fill()

turtlebot.teleport(-75, 150)
turtlebot.setheading(0)
turtlebot.fillcolor("blue")
turtlebot.begin_fill()
turtlebot.circle(50)
turtlebot.end_fill()

turtlebot.teleport(-75, 200)
turtlebot.setheading(270)
turtlebot.pensize(4)
turtlebot.pencolor("blue")
turtlebot.forward(150)
turtlebot.left(45)
turtlebot.forward(100)
turtlebot.teleport(-75,50)
turtlebot.setheading(225)
turtlebot.forward(100)
turtlebot.teleport(-75,150)
turtlebot.setheading(225)
turtlebot.forward(100)
turtlebot.teleport(-75,150)
turtlebot.setheading(315)
turtlebot.forward(100)


turtlebot.screen.mainloop()